spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ES?useUnicode=true&amp&characterEncoding=utf8&amp&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl